### ISSUE TITLE
The owo bot is offline

### ISSUE THREAD

**Issue by MontseGreenleaf** [juliettebee/owoTeam#1]
Hey! So I had the owo bot in my server but I am not sure if it's for the spam that someone did that it wont work anymore and it keeps appears offline. I've tried kicking the bot and re-inviting it to the server but it still wont work. How can I get it to work again?

**Comment by juliettebee** [comment]
This repo isn’t the official Owo repo and this question is more suited for the [support discord](https://discord.gg/owobot). Where this is posted,
> Slight hiccup, OwO is currently restarting!

(#announcements)
So nothing you can do but wait :)
